kind: Job
apiVersion: batch/v1
metadata:
  name: pravega-benchmark-throughput-1  # better name the job with configs
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pravega-benchmark
          # You must set the image below to a valid value.
          image: jxndyy1219/pravega-benchmark:0.8.2   # prefer to use your own image
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          args: [
            "-controller", "tcp://prvg-pravega-pravega-controller:9090", # get controller clusterIP: kb get svc --all-namespaces
            "-consumers", "1",
            "-scope", "lil58",
            "-stream", "benchmark1",
            "-segments", "3",
            "-producers", "3",
            #"-events", "1000000",
            "-time", "3600",  # Number of seconds to run
            "-size", "1000",
            "-throughput", "30" # MiB/sec
          ]
          env:
            - name: JAVA_OPTS
              value: "-Xmx2g -Xms1g"
