kind: Job
apiVersion: batch/v1
metadata:
  name: pravega-benchmark-test-large-test
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pravega-benchmark
          # You must set the image below to a valid value.
          image: devops-repo.isus.emc.com:8116/nautilus/pravega-benchmark:performance  # prefer to use your own image
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          args: [
            "-controller", "tcp://objectstore-pravega-pravega-controller:9090", # get controller clusterIP: kb get svc --all-namespaces
            "-consumers", "1",
            "-scope", "TEST-NEW-SCOPE8",
            "-stream", "benchmark8",
            #"-streamNum","20",
            "-segments", "32",
            "-producers", "1",
            #"-events", "100",
            "-time", "43200",  # Number of seconds to run
            "-size", "1000",
            "-throughput", "60" # MiB/sec
          ]
          env:
            - name: JAVA_OPTS
              value: "-Xmx2g -Xms1g"
