kind: Job
apiVersion: batch/v1
metadata:
  name: pravega-benchmark-128-10p0c3s  # better name the job with configs
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pravega-benchmark
          # You must set the image below to a valid value.
          image: aaronwuw/pravega-benchmark:0.6.1   # prefer to use your own image
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          args: [
            "-controller", "tcp://10.97.90.40:9090", # get controller clusterIP: kb get svc --all-namespaces
            #"-consumers", "10",
            "-scope", "aaron",
            "-readcsv", "/opt/pravega-benchmark/bin/read-perf.csv",
            "-writecsv","/opt/pravega-benchmark/bin/write-perf.csv",
            "-recreate","false",
            "-stream", "benchmark3",
            "-segments", "3",
            "-producers", "10",
            #"-events", "1000000",
            "-time", "600",  # Number of seconds to run
            "-size", "128",
            "-throughput", "-1" # MiB/sec
          ]
          env:
            - name: JAVA_OPTS
              value: "-Xmx2g -Xms1g"